### PR TITLE
(MAINT) Bump for new release

### PR DESCRIPTION
**Pull request by cdenneen**

### CODE REVIEW

**Comment by kevpl** [comment]
Hi @cdenneen, apologies for the gap in looking at this. Awesome that you found something that will auto-generate these entries for the changelog!

I assume that this won't happen automatically when merged, but will need new "bump for new release PRs" every time we're looking to run it? That is until we incorporate this into the jenkins release jobs, of course?

**Comment by cdenneen** [comment]
@kevpl I would guess normal contributor might not bump for release but they could... in which they would bump and update the CHANGELOG with a rake task. Obviously if Jenkins is doing your releases then it could run this rake task instead as part of it's release process.

**Comment by kevpl** [comment]
@cdenneen I like this code, & we've created a [ticket (QENG-6271)](https://tickets.puppetlabs.com/browse/QENG-6271) in order to do the work of setting up automation to run _github_changelog_generator_ as a part of beaker-aws's release.

There's one hitch before we merge your code as-is though. Our release jobs will fail if the version doesn't change when they're run, so you'll need to take away the actual version number change you have in this PR. I know that you need it to be the number it is for the CHANGELOG to make sense, but we'll make sure that happens when we run the release job, or do whatever work is needed to make it consistent.

**Comment by pinkypie** [comment]
Last comment still current

**Comment by cdenneen** [comment]
I’ll take a look tomorrow.

**Comment by cdenneen** [comment]
CHANGELOG removed

**Comment by kevpl** [comment]
@cdenneen I'm going to spend some time on this this week to create a rake task to make this easy to use for a job. I can either submit that as a PR to your branch or we can close this PR for that one. Which would you prefer?

**Comment by cdenneen** [comment]
please submit PR back to this and will merge

**Comment by kevpl** [comment]
@cdenneen apologies for the big delay here. I've submitted a PR to your branch at your fork for the rake tasks: https://github.com/cdenneen/beaker-aws/pull/1. Let me know if you have any issues or comments with that there, & once that's done we can come back to this one to push it forward.

**Pull request merged**
