### PR TITLE
(BKR-1244) Set vmhostname to host.name since host[:name] is awlays nil

### PR DESCRIPTION
**Pull request by samwoods1**

### CODE REVIEW

**Comment by ericwilliamson** [comment]
Jenkins, test this please

**Comment by ericwilliamson** [comment]
@samwoods1 Can you please update the commit message and title to explain what this change does, what was broken, and how this fixes it please

**Comment by ericwilliamson** [comment]
Jenkins, test this please

**Comment by ericwilliamson** [comment]
@samwoods1 spec tests are failing with

```
Failures:

  1) Beaker::AwsSdk#set_hostnames for each host sets the the vmhostname to the beaker config name for each host
     Failure/Error: expect(host[:vmhostname]).to eq(host[:name])

       expected: "prettyponyprincess"
            got: "vm1"

       (compared using ==)
     # ./spec/beaker/hypervisor/aws_sdk_spec.rb:644:in `block (5 levels) in <module:Beaker>'
     # ./spec/beaker/hypervisor/aws_sdk_spec.rb:643:in `each'
     # ./spec/beaker/hypervisor/aws_sdk_spec.rb:643:in `block (4 levels) in <module:Beaker>'

```

**Comment by samwoods1** [comment]
@puppetlabs-jenkins test this please

**Comment by samwoods1** [comment]
@ericwilliamson Hmm, looks like this pipeline isn't set up to run tests automatically?  I fixed the unit test.

**Comment by ericwilliamson** [comment]
Jenkins, test this please

**Comment by er0ck** [comment]
👍

**Pull request merged**
